name: Integration Tests with Cypress

on: [push]

jobs:
  cypress-local-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run UI & API integrations
        uses: cypress-io/github-action@v2
        with:
          config: baseUrl=http://localhost:5000
          command: yarn cypress:run
          browser: chrome
          build: yarn build
          start: yarn start:prod
          spec: cypress/tests/**/*
          wait-on: "http://localhost:5000"
