name: Integration Tests with Cypress

on:
  push:
    paths-ignore:
      - "doc/**"

jobs:
  cypress-local-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run UI & API integrations
        uses: cypress-io/github-action@v2
        with:
          config-file: cypress/cypress-ci.json
          command: yarn cypress:run
          browser: chrome
          build: yarn build
          start: yarn start:prod
          spec: cypress/tests/**/*
          wait-on: "http://localhost:5000"
